### ISSUE TITLE
Memroy leaks

### ISSUE THREAD

**Issue by hitosu** [albertosantini/node-rio#39]
Memory leaks in `./lib/crypt.js` : there are lots of variables without var, const or let.

**Comment by yapus** [comment]
mocha output:
```
 Error: global leaks detected: i, j, b, k, inbit, obit
```

**Comment by albertosantini** [comment]
Thanks for the feedback.

As you noticed that source code is a third-party source code. 
I didn't modify it, because finally it would be harder to stay in sync with the original source.

I disabled the linter, because there are many errors and warnings.

Also `rio` has been using that code in a node module (and not in the browser): so the variables without any definition (var, const or let) are global in the module.

If you have any contribution to replace it with a better and maintained , you are welcome.
